# By default, the flannel install-cni-plugin init container would copy the flannel binary into /opt/cni/bin
# but /opt is linked to /usr/lib/opt and /usr is mount ro. So we need to do this work upfront and remove the init container.
# For now, we are putting the flannel k8s manifest in /usr, however, this may change to something better.

#TODO: Add support for other architectures by conditionally adding the correct flanneld bin.

add-files: [
  [ "flannel", "/usr/lib/opt/cni/bin/flannel" ],
  [ "kube-flannel.yml", "/usr/kube-flannel.yaml" ],
]

#postprocess:
#  - |
#    #!/usr/bin/env bash
#
#    # Prefetch iamges
#    ctr images pull docker.io/flannel/flannel:v0.21.4
#    ctr images pull docker.io/flannel/flannel-cni-plugin:v1.1.2
    
